### ISSUE TITLE
Incompatibility with Iris

### ISSUE THREAD

**Issue by Aquaeyes** [magistermaks/mod-led#1]
[crash-2022-01-16_14.36.54-client.txt](https://github.com/magistermaks/mod-led/files/7876499/crash-2022-01-16_14.36.54-client.txt)

**Versioning Information**
Minecraft version 1.18, Fabric 0.12.12, LED Version 1.2.0, Sodium Version 0.4.0.alpha6+build.14, Iris version 1.1.5, Indium version 1.0.2-alpha2.

**Issue Description**
LED seems to be incompatible with Iris. Removing either mod solves the crash.

**Steps To Reproduce**
Run game with Indium, Sodium, Iris, and LED installed. Crashes without going to loading screen.

**Comment by magistermaks** [comment]
Thanks for the report, I will look into this

**Comment by magistermaks** [comment]
LED internally uses JMX which uses FREX which is not compatible with other rendering systems than Canvas, so this is not resolvable
until now it thought that is worked if indium was used but this is sadly not the case, i will remove the note about indium from the CF page, thanks for bringing this to my attention
