### ISSUE TITLE
KNOWN ISSUE - Sodium/Iris/Indium incompatibility 

### ISSUE THREAD

**Issue by magistermaks** [magistermaks/mod-led#2]
**As of 1.18 LED became incompatible with Sodium/Iris/Indium**, that is because an embedded library called JMX (Json Model Extensions) started depending on FREX - an extended rendering API from the Canvas family, for the time being (and the foreseeable future) there is no compatibility layer between Sodium and FREX similar to how Indium brings support for FRAPI into Sodium. Because of that i will try to stop depending on JMX and either:
- Fork JMX 1.17 (prior to the breaking change) and update it to 1.18, and then depend on that more compatible version of JMX, OR
- Directly use the Fabric Rendering API (FRAPI) without the use of a library similar to JMX  

**I'm working on a solution**, but both of those approaches require a lot of work, so it can take some time to fix this issue.

**Comment by SangeloDev** [comment]
You could add Sodium, Indium, etc. as incompatibilities in the fabric.mod.json file.

**Comment by magistermaks** [comment]
This ideally should be done on JMX's (or FREX's) part

**Comment by magistermaks** [comment]
Resolved in commit 732468875beaa53e1f379c52cb1c71e1fca1461e, as of v1.2.3 LED should support Sodium and Iris through Indium compatibility layer
