### ISSUE TITLE
Incompatible with Accurate Maps, causing commands to be inexecutable by the client.

### ISSUE THREAD

**Issue by lizfinite** [magistermaks/mod-led#6]
Issue: using both of these mods makes you unable to execute commands

Steps to reproduce:
- Install Mods
- Open up to single player world with cheats
- Try to execute changing your gamemode

Here's a log with only the two mods (and required dependencies): https://paste.ee/p/lTCWn

**Comment by magistermaks** [comment]
kinda late but i fixed it, it's a bug in the library LED uses 
for now you will need to download the patched JMXL lib (https://www.curseforge.com/minecraft/mc-mods/jmxl) and place it alongside led
i will release LED with this new patched JMXL version at some point too
