### ISSUE TITLE
[Suggestion] Make the mod compatible with Shimmer

### ISSUE THREAD

**Issue by Delfite** [magistermaks/mod-led#7]
Make your mod compatible with this mod: https://www.curseforge.com/minecraft/mc-mods/shimmer

The lights from this mod look good on their own, but they'd look way better if they were made compatible with Shimmer. Not only would the lights give off colored light, but they'd also have a bloom effect applied to them making it even cooler to look at and use in builds.

**Comment by magistermaks** [comment]
Sounds cool :+1: will definitely look into it

**Comment by Delfite** [comment]
Any progress on this so far? Not trying to rush, just curious.

**Comment by magistermaks** [comment]
no progress sorry, i haven't worked on anything modding related in quite some time now,  
but once i do return to it, this will very likely get added

**Comment by magistermaks** [comment]
Implemented in https://github.com/magistermaks/mod-led/commit/fb539a5baeb2dcb1f7a039d2b214bd141801d610

**Comment by magistermaks** [comment]
This feature was added to version 1.5.0 of the mod - https://modrinth.com/mod/led/version/1.5.0
